### ISSUE TITLE
chap 6 deleted

### ISSUE THREAD

**Issue by imranashraf** [dmitsot/computational_mathematics#1]
@dmitsot thank you for the very useful repo. Recently chap 6 got deleted. should we expect an update on this chapter?

**Comment by dmitsot** [comment]
Dear Imran, I have uploaded a new version of the file. I apologise for that. Indeed, I am preparing a new edition with corrections and updated code. Some of the functions have been deprecated in last version of SciPy 1.12. Thank you for using it and please do not hesitate to contact me if you detect any issues.

**Comment by imranashraf** [comment]
Dear @dmitsot. thank you for the prompt response. looking forward. I am using it for teaching Numerical Computing to CS students. I must say, the book as well the accompanied notebooks not only nicely cover the background, provide theoretical foundation at reasonable depth but also dive deeper into the practical hands on aspects of computational math. By going through this material, I believe, CS students will know the depth of "Computational mathematics" and not just its name.
